app_login/urls.py
from django.urls import path, include
from . import views

app_name = 'app_login'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
]

app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    

app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label= 'Email',max_length=254, required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm

def sign_up(request):
    form = SignUpForm()
    registered = False
    
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
            
    dict = {'form': form, 'registered': registered}
    return render(request, 'app_login/sign_up.html', context=dict)
            

def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
    return render(request, 'app_login/sign_in.html', context={'form': form})

@login_required
def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/app_login/sign_in.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
  Log In
{% endblock %}
{% block body_block %}
  <h2>Login:</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success btn-sm">Login</button>
  </form>
{% endblock %}

templates/app_login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
  Sing Up
{% endblock %}
{% block body_block %}
  {% if registered %}
    <div class="alert alert-success">
      Account Created Succesully! <a href="{% url 'app_login:sign_in' %}">Login Here</a>
    </div>
  {% else %}
    <h2>Create New Account:</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success btn-sm">Create Account</button>
    </form>
    <br />
    <p>
      Already have an account? <a href="{% url 'app_login:sign_in' %}">Login</a>
    </p>
  {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title_block %} Blogs {% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'app_login:sign_out' %}">Log Out</a>
                </li>
                {% else %}
                <li>
                    <a class="nav-link" href="{% url 'app_login:sign_up' %}">Sign Up</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'app_login:sign_in' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        <div class="container" style="padding-top: 20px;">
            {% block body_block %}
            {% endblock %}
        </div>
            
    </body>
</html>